/* SIMD86 — Single Instruction, Multiple Decks.
 *
 * A slide deck that is *executed*, not rendered by a runtime: this C is
 * compiled mov-only (llvm-mov) and run inside movie86 / turbo86. Every
 * pixel that reaches the screen is produced by `mov`.
 *
 * Slides are plain image data linked in via deck_data.s (generated by
 * gen_deck.py from deck.toml). Each slide carries its own video mode +
 * framebuffer address + pixel count, so a deck can change resolution
 * between slides — start light (e.g. 320x200) and bump to a heavier mode
 * later. This program is the flipbook: poll input, move an index, and on
 * a change re-issue set_video_mode when the resolution differs, then blit
 * the slide. Drawing only on a change keeps the poll loop cheap.
 *
 * movie86's input is generic key codes; the slide meaning lives here —
 * Right / Space / PageDown advance, Left / PageUp go back, Home / End
 * jump to the ends.
 */

/* movie86 generic key codes (core::abi_host KEY_*). */
#define KEY_NONE      0x00
#define KEY_BACKSPACE 0x08
#define KEY_ENTER     0x0D
#define KEY_SPACE     0x20
#define KEY_LEFT      0x80
#define KEY_RIGHT     0x81
#define KEY_PAGE_UP   0x84
#define KEY_PAGE_DOWN 0x85
#define KEY_HOME      0x86
#define KEY_END       0x87

extern void set_video_mode(unsigned mode);
extern void mmap_request(unsigned packed);
extern int poll_input(void);

/* Slide table + memory image, supplied by deck_data.s (generated). */
extern const unsigned char slides_data[]; /* all slides' RGBA, concatenated */
extern const int n_slides;
extern const unsigned int slide_mode[]; /* video mode byte per slide */
extern const unsigned int slide_addr[]; /* framebuffer guest addr per slide */
extern const unsigned int slide_npix[]; /* pixel count (w*h) per slide */
extern const unsigned int slide_off[];  /* byte offset into slides_data */

/* Pack (addr, pages) for the mov-only ABI mmap_request call. */
#define ABI_MMAP_PACK(addr, pages) ((unsigned)(addr) | (unsigned)((pages) - 1))

static unsigned pages_for(unsigned bytes)
{
    return (bytes + 0xFFF) >> 12;
}

static void show(int i)
{
    /* slide_addr is a 32-bit guest address; cast via unsigned long so the
     * (32-bit -m32) build is exact and host clang doesn't warn about an
     * int→pointer width mismatch. */
    unsigned int *fb = (unsigned int *)(unsigned long)slide_addr[i];
    const unsigned int *src = (const unsigned int *)(slides_data + slide_off[i]);
    int n = slide_npix[i];
    int k;
    for (k = 0; k < n; k++) {
        fb[k] = src[k];
    }
}

int main(void)
{
    int idx, prev, k, i;
    int cur_mode, seen;

    /* Reserve every *distinct* framebuffer region up front. Slides that
     * share a resolution share a framebuffer address, so request each
     * address only once: a naive per-slide request (n_slides times) would
     * blow turbo86's dynamic-region cap (mmapMaxRegions = 32) — the deck's
     * PT_LOAD segments already consume some of that budget when turbo86
     * maps the ELF. On movie86 (wasm) the FB pages are PT_LOAD-mapped
     * already so this is a no-op; on turbo86 the mmap is what keeps the
     * first write from faulting. */
    for (i = 0; i < n_slides; i++) {
        seen = 0;
        for (k = 0; k < i; k++) {
            if (slide_addr[k] == slide_addr[i]) {
                seen = 1;
                break;
            }
        }
        if (!seen) {
            mmap_request(ABI_MMAP_PACK(slide_addr[i], pages_for(slide_npix[i] * 4)));
        }
    }

    idx = 0;
    cur_mode = (int)slide_mode[0];
    set_video_mode(slide_mode[0]);
    show(0);

    for (;;) {
        k = poll_input();
        prev = idx;

        /* Enter / Backspace are fallbacks alongside the arrows (some
         * remotes / setups only send those). */
        if (k == KEY_RIGHT || k == KEY_SPACE || k == KEY_PAGE_DOWN || k == KEY_ENTER) {
            if (idx < n_slides - 1) {
                idx++;
            }
        }
        if (k == KEY_LEFT || k == KEY_PAGE_UP || k == KEY_BACKSPACE) {
            if (idx > 0) {
                idx--;
            }
        }
        if (k == KEY_HOME) {
            idx = 0;
        }
        if (k == KEY_END) {
            idx = n_slides - 1;
        }

        if (idx != prev) {
            /* Re-issue set_video_mode only when the resolution changes
             * (the heavier-mode slide is where the boost matters). */
            if ((int)slide_mode[idx] != cur_mode) {
                cur_mode = (int)slide_mode[idx];
                set_video_mode(slide_mode[idx]);
            }
            show(idx);
        }
    }

    return 0;
}
