#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pillow"]
# ///
"""Convert a SIMD86 deck spec (+ images) into the guest memory image.

Run with uv (`uv run gen_deck.py ...`) — the PEP 723 header above pins
Python + Pillow so the toolchain is reproducible without a manual venv.

Input:  a deck.toml listing slides top-to-bottom, each with an image and
        a resolution (see deck.toml for the format).
Output (into the dir given as -o, default cwd):
  - deck.bin     raw RGBA, one frame per slide, concatenated. This is the
                 "memory image" the renderer blits from.
  - deck_data.s  `.incbin "deck.bin"` + a slide table the mov-only
                 renderer (deck.c) indexes:
                   n_slides   : .long  slide count
                   slide_mode : .long[] video mode byte per slide
                   slide_addr : .long[] framebuffer guest address per slide
                   slide_npix : .long[] pixel count (w*h) per slide
                   slide_off  : .long[] byte offset into slides_data

Pixel byte order is R,G,B,A (little-endian u32 0xAABBGGRR) — what movie86
and JS putImageData expect.

Resolution -> (video mode, framebuffer address) must match movie86's
FRAMEBUFFER_MODES (movie86.mjs). When the resolution changes between
slides the renderer re-issues set_video_mode with the new mode byte.

Usage:  gen_deck.py DECK_TOML -o OUT_DIR
"""

import argparse
import os
import struct
import sys
import tomllib

# (width, height) -> (mode byte, framebuffer guest addr). Mirrors
# movie86.mjs FRAMEBUFFER_MODES; keep in sync.
MODES = {
    (320, 200): (0x13, 0x000A0000),
    (640, 480): (0x12, 0x00100000),
    (640, 350): (0x10, 0x00300000),
    (800, 600): (0x6A, 0x00400000),
    # 16:9 widescreen (matches movie86.mjs).
    (480, 270): (0x70, 0x00800000),
    (960, 540): (0x71, 0x00A00000),
    (1280, 720): (0x72, 0x00C00000),
    (1920, 1080): (0x73, 0x01000000),
}


def parse_color(spec):
    """`color:RRGGBB` -> opaque RGBA bytes for one pixel."""
    hexs = spec[len("color:"):]
    if len(hexs) != 6:
        raise ValueError(f"color must be RRGGBB, got {spec!r}")
    r, g, b = (int(hexs[i:i + 2], 16) for i in (0, 2, 4))
    return struct.pack("<BBBB", r, g, b, 255)


def slide_rgba(image, w, h, base_dir, bg=(0, 0, 0)):
    """Produce w*h*4 RGBA bytes for one slide.

    Images are fit into (w, h) **preserving aspect ratio** and centered
    (letterboxed with `bg`), so a 16:9 source isn't squashed into a 4:3
    or 8:5 framebuffer mode. `color:` placeholders fill the whole frame.
    """
    if image.startswith("color:"):
        return parse_color(image) * (w * h)
    from PIL import Image  # provided by the PEP 723 dependency
    path = image if os.path.isabs(image) else os.path.join(base_dir, image)
    src = Image.open(path).convert("RGBA")
    # Scale to fit inside (w, h) without distortion, then paste centered
    # onto an opaque background of the target size.
    fitted = src.copy()
    fitted.thumbnail((w, h), Image.LANCZOS)
    canvas = Image.new("RGBA", (w, h), (bg[0], bg[1], bg[2], 255))
    canvas.paste(fitted, ((w - fitted.width) // 2, (h - fitted.height) // 2), fitted)
    return canvas.tobytes()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("deck_toml")
    ap.add_argument("-o", "--out-dir", default=".")
    args = ap.parse_args()

    base_dir = os.path.dirname(os.path.abspath(args.deck_toml))
    with open(args.deck_toml, "rb") as f:
        spec = tomllib.load(f)
    slides = spec.get("slides", [])
    if not slides:
        sys.exit(f"gen_deck: no [[slides]] in {args.deck_toml}")

    blob = bytearray()
    modes, addrs, npix, offs = [], [], [], []
    for i, s in enumerate(slides, start=1):
        res = s["resolution"]
        try:
            w, h = (int(x) for x in res.lower().split("x"))
        except ValueError:
            sys.exit(f"gen_deck: slide {i}: bad resolution {res!r}")
        if (w, h) not in MODES:
            sys.exit(f"gen_deck: slide {i}: resolution {res} is not a "
                     f"movie86 framebuffer mode {sorted(MODES)}")
        mode, addr = MODES[(w, h)]
        data = slide_rgba(s["image"], w, h, base_dir)
        assert len(data) == w * h * 4
        offs.append(len(blob))
        blob.extend(data)
        modes.append(mode)
        addrs.append(addr)
        npix.append(w * h)

    with open(f"{args.out_dir}/deck.bin", "wb") as f:
        f.write(blob)

    def longs(name, vals):
        body = "".join(f"    .long {v}\n" for v in vals)
        return f".globl {name}\n.align 4\n{name}:\n{body}"

    with open(f"{args.out_dir}/deck_data.s", "w") as f:
        f.write(
            "/* Generated by gen_deck.py — do not edit. Slide memory image\n"
            " * (.incbin) + slide table. */\n"
            ".section .rodata\n"
            ".globl slides_data\n.align 4\nslides_data:\n"
            '    .incbin "deck.bin"\n'
            + longs("n_slides", [len(slides)])
            + longs("slide_mode", modes)
            + longs("slide_addr", addrs)
            + longs("slide_npix", npix)
            + longs("slide_off", offs)
        )

    print(f"gen_deck: {len(slides)} slides, {len(blob)} bytes "
          f"({', '.join(f'{m:#x}@{a:#x}' for m, a in zip(modes, addrs))}) "
          f"-> {args.out_dir}/deck.bin")


if __name__ == "__main__":
    main()
