#!/usr/bin/env python3
"""Generate a placeholder SIMD86 deck as raw RGBA + an asm blob.

SIMD86 slides are just image data; the mov-only renderer (deck.c) blits
the current one to movie86's mode-13h framebuffer. This script makes a
few procedurally-drawn 320x200 placeholder slides so the flip mechanism
can be built and tested before any real slide art exists — swap in real
images later by pointing the build at PNG-derived RGBA instead.

Outputs (into the dir given as argv[1], default cwd):
  - deck.bin       raw RGBA, n_slides * 320*200*4 bytes, slide-major
  - deck_data.s    `.incbin "deck.bin"` + an `n_slides` long, so the C
                   side sees `extern const unsigned slides_data[]` and
                   `extern const int n_slides` without the compiler ever
                   parsing a giant array literal.

Pixel byte order is R,G,B,A (little-endian u32 0xAABBGGRR) — what the
canvas examples and JS putImageData expect.
"""

import sys
import struct

W, H = 320, 200

# Distinct opaque background colours, one per slide. (R, G, B)
BACKGROUNDS = [
    (30, 30, 46),    # slide 1 — dark indigo
    (40, 54, 24),    # slide 2 — deep green
    (60, 30, 30),    # slide 3 — maroon
    (24, 40, 54),    # slide 4 — steel blue
]
FG = (220, 220, 220)  # marker / border colour


def px(r, g, b, a=255):
    return struct.pack("<BBBB", r, g, b, a)


def make_slide(index, n):
    """Build one slide: solid background, a light border, and `index+1`
    filled squares along the top — a dead-simple 'which slide am I'
    indicator that's obvious even without text rendering."""
    bg = BACKGROUNDS[index % len(BACKGROUNDS)]
    bg_px = px(*bg)
    fg_px = px(*FG)
    buf = bytearray(bg_px * (W * H))

    def put(x, y, p):
        if 0 <= x < W and 0 <= y < H:
            off = (y * W + x) * 4
            buf[off:off + 4] = p

    # 2px border.
    for x in range(W):
        for t in range(2):
            put(x, t, fg_px)
            put(x, H - 1 - t, fg_px)
    for y in range(H):
        for t in range(2):
            put(t, y, fg_px)
            put(W - 1 - t, y, fg_px)

    # index+1 filled 16x16 markers across the top-left.
    sq = 16
    gap = 8
    for m in range(index + 1):
        x0 = 16 + m * (sq + gap)
        y0 = 24
        for dy in range(sq):
            for dx in range(sq):
                put(x0 + dx, y0 + dy, fg_px)

    return bytes(buf)


def main():
    out_dir = sys.argv[1] if len(sys.argv) > 1 else "."
    n = int(sys.argv[2]) if len(sys.argv) > 2 else 4
    n = max(1, min(n, len(BACKGROUNDS)))

    blob = b"".join(make_slide(i, n) for i in range(n))
    with open(f"{out_dir}/deck.bin", "wb") as f:
        f.write(blob)

    with open(f"{out_dir}/deck_data.s", "w") as f:
        f.write(
            "/* Generated by gen_deck.py — do not edit. Raw RGBA slide\n"
            " * data linked straight in via .incbin so the C compiler\n"
            " * never sees a giant array literal. */\n"
            ".section .rodata\n"
            ".globl slides_data\n"
            ".align 4\n"
            "slides_data:\n"
            '    .incbin "deck.bin"\n'
            ".globl n_slides\n"
            ".align 4\n"
            f"n_slides:\n    .long {n}\n"
        )
    print(f"gen_deck: {n} slides, {len(blob)} bytes → {out_dir}/deck.bin")


if __name__ == "__main__":
    main()
