#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pymupdf"]
# ///
"""Render a PDF deck into per-slide PNGs + a deck.toml for SIMD86.

This is the front of the build pipeline: a normal presentation PDF in,
the SIMD86 deck spec (PNGs + deck.toml) out. From there build-deck.sh
turns it into the mov-only deck.elf:

    pdf_to_deck.py talk.pdf -o kvm2026-kansai
    ./build-deck.sh                 # reads kvm2026-kansai/deck.toml

One PNG per page is written as `slideNN.png` (1-based) into the output
dir, and a `deck.toml` listing them in order. Resolution per slide is a
movie86 framebuffer mode (see gen_deck.py MODES); pages are 16:9 in
practice, so the 16:9 modes are the defaults.

The "acceleration boost" story wants the deck to start cheap and get
heavy, so by default slide 1 is rendered at a LOW res and the rest at a
HIGH res — the first heavy (high-res) blit on movie86 is visibly slow,
which is the cue to hit the boost. Override with --res / --first-res, or
--uniform to render every slide at the same (high) res.

Usage:
  pdf_to_deck.py INPUT.pdf -o OUTDIR
                 [--res WxH] [--first-res WxH] [--uniform]
"""

import argparse
import os
import sys

# movie86 framebuffer modes (must match gen_deck.py MODES /
# movie86.mjs FRAMEBUFFER_MODES). Used to validate --res choices.
VALID_RES = {
    "320x200", "640x480", "640x350", "800x600",
    "320x180", "480x270", "960x540", "1280x720", "1920x1080",
}
# Resolution compromise: a 1280x720 deck bakes ~160 MiB of RGBA into the
# ELF's .rodata, which overruns turbo86's 16 MiB stub region on the
# acceleration-boost handover (see simd/test-deck-size.py). 320x180 keeps
# the whole deck under that budget so the boost works on stock turbo86 —
# lower-res, but still true 16:9 (no letterboxing). Both defaults are the
# same so the deck is uniform; bump --res once turbo86 grows its region.
DEFAULT_FIRST_RES = "320x180"   # 16:9, fits the boost region
DEFAULT_RES = "320x180"         # 16:9, fits the boost region


def parse_res(s):
    if s not in VALID_RES:
        sys.exit(f"pdf_to_deck: resolution {s!r} is not a movie86 mode "
                 f"{sorted(VALID_RES)}")
    w, h = (int(x) for x in s.lower().split("x"))
    return w, h


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("pdf")
    ap.add_argument("-o", "--out-dir", required=True,
                    help="dir to write slideNN.png + deck.toml into")
    ap.add_argument("--res", default=DEFAULT_RES,
                    help=f"resolution for slides (default {DEFAULT_RES})")
    ap.add_argument("--first-res", default=None,
                    help="resolution for slide 1 only (default "
                         f"{DEFAULT_FIRST_RES}; ignored with --uniform)")
    ap.add_argument("--uniform", action="store_true",
                    help="render every slide at --res (no cheap first slide)")
    args = ap.parse_args()

    import fitz  # PyMuPDF, from the PEP 723 dependency

    res_w, res_h = parse_res(args.res)
    first = args.res if args.uniform else (args.first_res or DEFAULT_FIRST_RES)
    first_w, first_h = parse_res(first)

    os.makedirs(args.out_dir, exist_ok=True)
    doc = fitz.open(args.pdf)
    n = doc.page_count
    if n == 0:
        sys.exit("pdf_to_deck: PDF has no pages")

    lines = [
        "# Generated by pdf_to_deck.py — re-run to regenerate from the PDF.",
        "# Edit the source PDF, not this file (manual tweaks are lost).",
        "",
    ]
    for i in range(n):
        w, h = (first_w, first_h) if i == 0 else (res_w, res_h)
        page = doc.load_page(i)
        # Fit the page into (w, h) preserving aspect ratio: pick the
        # scale that maps the page's longer side to the target, render at
        # that zoom, then gen_deck letterboxes any leftover to the exact
        # framebuffer size. Rendering near the target size keeps text
        # crisp without producing a needlessly huge intermediate PNG.
        rect = page.rect
        zoom = min(w / rect.width, h / rect.height)
        pix = page.get_pixmap(matrix=fitz.Matrix(zoom, zoom), alpha=False)
        name = f"slide{i + 1:02d}.png"
        pix.save(os.path.join(args.out_dir, name))
        lines += ["[[slides]]", f'image = "{name}"',
                  f'resolution = "{w}x{h}"', ""]

    with open(os.path.join(args.out_dir, "deck.toml"), "w") as f:
        f.write("\n".join(lines))

    res_note = (f"all {args.res}" if args.uniform
                else f"slide 1 {first}, rest {args.res}")
    print(f"pdf_to_deck: {n} pages -> {args.out_dir}/slide*.png + deck.toml "
          f"({res_note})")


if __name__ == "__main__":
    main()
