[package]
name = "rust-mov-base64-decode"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "rust-mov-base64-decode"
path = "src/main.rs"

[lib]
crate-type = ["staticlib"]
path = "src/main.rs"

[dependencies]
base64 = { version = "0.22", default-features = false }

[profile.release]
panic = "abort"
opt-level = 1
codegen-units = 1
overflow-checks = false
debug = false
strip = false
lto = false

[profile.dev]
panic = "abort"
overflow-checks = false
