#!/usr/bin/env bash
# Test wasm-as against committed .o goldens.
#
# For each tests/goldens/*.s (the rcc/cpp output we already certified),
# run build/as.js and assert the resulting ELF32 .o is byte-identical to
# tests/goldens-o/*.o (regenerated by scripts/regen-goldens-o.sh from
# the host /usr/bin/as). Mirrors tests/run.sh.

set -uo pipefail

here="$(cd "$(dirname "$0")/.." && pwd)"
goldens_s="$here/tests/goldens"
goldens_o="$here/tests/goldens-o"
asjs="$here/build/as.js"

if [ -z "${EMSDK:-}" ] && [ -f "$HOME/emsdk/emsdk_env.sh" ]; then
    # shellcheck disable=SC1091
    EMSDK_QUIET=1 source "$HOME/emsdk/emsdk_env.sh" > /dev/null
fi

if [ ! -f "$asjs" ]; then
    echo "FAIL: $asjs missing; run 'make build-wasm-as' first" >&2
    exit 1
fi

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

pass=0; fail=0
for s in "$goldens_s"/*.s; do
    name="$(basename "$s" .s)"
    golden="$goldens_o/$name.o"
    if [ ! -f "$golden" ]; then
        echo "SKIP $name (no .o golden — run 'make goldens-o')"
        continue
    fi
    out="$tmp/$name.o"
    if ! node "$asjs" --32 -mx86-used-note=no -o "$out" "$s" > "$tmp/$name.out" 2>&1; then
        echo "FAIL $name — wasm-as exited non-zero"
        sed 's/^/  | /' "$tmp/$name.out"
        fail=$((fail+1))
        continue
    fi
    if cmp -s "$out" "$golden"; then
        echo "PASS $name ($(stat -c %s "$out") bytes)"
        pass=$((pass+1))
    else
        echo "FAIL $name — wasm-as .o differs from golden"
        echo "  | native=$(stat -c %s "$golden") wasm=$(stat -c %s "$out")"
        fail=$((fail+1))
    fi
done

echo
echo "results: $pass passed, $fail failed"
[ "$fail" -eq 0 ]
