[package]
name = "rust-mov-qoi-decode"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "rust-mov-qoi-decode"
path = "src/main.rs"

[dependencies]
qoi = { version = "0.4", default-features = false }

[profile.release]
panic = "abort"
opt-level = 1
codegen-units = 1
overflow-checks = false
debug = false
strip = false
lto = false

[profile.dev]
panic = "abort"
overflow-checks = false
