; Stage 7b1 PoC fixture — bitwise XOR, register-register form.
;
; The `xor a, b` shape covers the same legalization path as `or rr`
; but indexes __mov_xor8_table. Same-reg XOR (`xor eax, eax`) — the
; idiomatic zero-clear — is NOT generated by SelectionDAG for this
; IR; it would arrive as a constant zero materialised via MOV32ri 0
; and never reach the legalize pass.

target triple = "mov-unknown-linux-gnu"

define i32 @xor_rr(i32 %a, i32 %b) {
  %r = xor i32 %a, %b
  ret i32 %r
}
